name: Fix PHP code styling

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          php-version: 8.4
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Run Pint
        run: vendor/bin/pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "style: fix code styling"
